Configuration:
  - Name: alice
    IP: 128.237.168.135
    Port: 12344
  - Name: bob
    IP: 128.237.169.148
    Port: 14255
  - Name: charlie
    IP: 128.2.130.19
    Port: 12998
  - Name: daphnie
    IP: 192.168.1.87
    Port: 1987

SendRules:
  - Action: drop
    Src: bob
    Dest: alice
    Kind: Ack
    ID: 4
  - Action: delay
    Kind: Request
  - Action: duplicate
    Kind: dup

ReceiveRules:
  - Action: delay
    Src: bob
